### ISSUE TITLE
Roadmap for V2

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-rando#297]
Here we go with the final roadmap for Geotrek V2 :

# Critical

### GLOBAL
- [x] add loaders for app

### HOMEPAGE
- [x] multilang home

### HEADER
- [x] open flat page dropdown on hover
- [x] Add share functionnality

### FLAT PAGES
- [x] Implement flat pages

### MAP
- [x] Smaller markers
- [x] Linear treks always 100% opacity but with border on hover (like V1)

### CATEGORIES FILTERS
- [x] Make types filters titles bigger

### RESULTS FILTERS
- [x] Add auto-completion to areas and states filters
- [x] Remove number of results on areas and states filters
- [x] Add Themes title above themes filters
- [x] Order geo filters by alpha
- [x] Add structure field

### RESULTS
- [x] Add results count on result liste
- [x] Make favorites a bit smaller
- [x] Themes icons should be at the bottom of the block in lighter grey
- [x] Interaction with map viewport filtering (greyscale)
- [x] Sort results by alpha order
- [x] Add date information on touristic events

### DETAIL
//// PICTURES
- [x] Lightbox on main picture click
- [ ] ~~Carousel for pictures thumbnails~~ (doesn't seems accurate)
- [x] Remove main pictures from thumbnails
- [x] Deactivate scroll for thumbnails

//// DESCRIPTION
- [x] Put main infos icons above the rest
- [x] Replace "Loop:" by "Departure/Arrival:"
- [x] Stylize ordered list for ref markers
- [x] Add missing informations (website / practicals informations) for touristics objects and events

//// RULES
- [x] Link rules block to rules flat pages

//// INFORMATION DESKS / CONTACT
- [x] Change icon
- [x] Force external links
- [x] Add placeholder image
- [x] Reset links style

//// LEARN MORE
- [x] Force external links

//// DETAIL - SIDEBAR
- [x] Fix 3D Rando (removing static paths and adding module export) --- `HEAVY DEV`
- [x] Add share functionnality

### DETAIL MAP
- [x] Activate POI's markers clustering
- [x] Replace POI's marker background with something less precise (not pointing on a specific palce on map)
- [x] Put Interests box in map container alowing it to be displayed in full-screen
- [x] Near-objects markers should have a tooltip

### POIS
- [x] Push them after others elements type (near/objects, practicies, etc...)
- [x] Hide them if not trek type
- [x] Open all POIs by default on desktop
- [x] Add attached files list
- [x] Add lightbox gallery for each poi
- [x] Add audio and video players opening in modal (Youtube/Vimeo + Soundcloud)

### NEAR OBJECTS
- [x] same display as results page but without themes and +infos

### RESULTS MAP
- [x] Add reset view control
- [x] Translate controls tooltips
- [ ] Add external informations
- [x] Add start point when line display for treks
- [x] Change start and end icons
- [x] Highlight clusters on result hover in list
- [x] Add tooltip on marker hover
- [x] Stylize clusters
- [x] Add map viewport filtering
- [x] ADD toggle gor viewport filtering

### OPTIONS
- [x] Add unique ID for each platform
- [x] Allow to hide Geo filters separatly

# Not critical for v2.0 but need to be added
### CATEGORIES
- [ ] Ability to split trekking by practices

### MAP
- [ ] Add multi tiles-layers depending on zoom
- [ ] Add MBTILES and GEOJSON custom layers support

### OPTIONS
- [ ] Minimap activation and zoom
- [ ] Allow to chose between stars and hearth for favorites

### DETAIL
//// LEARN MORE
- [ ] Better style

# Not critical
### CATEGORIES FILTERS
- [x] Open filters type if 2 or less type (is it consistent across platforms ?)

### CATEGORIES RESULTS
- [ ] On mobile tap on cat icon open the menu and activation-deactivation is done by clicking on name only

### DETAIL
//// TRANSPORTS / ACCESS
- [ ] Chose to make it take full width or half if only one active

### RESULTS MAP
- [ ] Add hierarchical format to tags filters

**Comment by camillemonchicourt** [comment]
About ADDITIONAL LAYERS, we didnt discussed how it would be done. 
In V1, we add to add some JS in footer.html.
A better way to do would be : https://github.com/makinacorpus/Geotrek-rando/issues/209

**Comment by leplatrem** [comment]
> A better way to do would be : #209
> 
Note: overlay layers via settings is available since django-leaflet 0.15.0
